server:
  port: 5561
spring:
  application:
    name: scala
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/practice?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 在没有连接可用的情况下等待超时时间
      connection-timeout: 30000
      # 核心连接池最大大小
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    # 设置创表引擎为Innodb，不然默认为MyiSam
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://zoe:zoe@127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
tools:
  doc:
    enable: true
    title: Scala服务
    group:
      enable: true
      service-list:
        - 用户模块:
            # 下拉选择时展示的名称
            desc: Scala模块
            # 跟随zuul网关路由的path而定，如上为：/demo/**，那么这里应该填demo
            url: scala
    global-headers:
      - name: token
        description: 请求头token
        required: false

